apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java-deployment
        image: acraksf7qlptmhmwvmc.azurecr.io/java:6c6eb75fc1a85e606757cac68e12973965ae1469
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi       
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: ClusterIP
  selector:
    app: java
  ports:
  - port: 2000
    targetPort: 2000